/**
 * Internal-only routes — called by other services (API gateway, outreach),
 * never exposed to the public internet.
 *
 * These endpoints skip JWT authentication because they are protected by
 * network-level isolation (Docker network / Kubernetes NetworkPolicy).
 */

import type { FastifyInstance } from "fastify";
import { z } from "zod";
import { sendTeamInviteEmail } from "../lib/email";

const InviteEmailSchema = z.object({
  to: z.string().email(),
  inviterName: z.string(),
  tenantName: z.string(),
  inviteToken: z.string(),
});

const QuoteSentEmailSchema = z.object({
  to: z.string().email(),
  recipientName: z.string(),
  quoteNumber: z.string(),
  totalAmount: z.string(),
  senderName: z.string(),
  companyName: z.string(),
});

export async function internalRoutes(server: FastifyInstance) {
  // POST /internal/send-invite — send a team invite email
  server.post("/send-invite", async (request, reply) => {
    const parsed = InviteEmailSchema.safeParse(request.body);
    if (!parsed.success) {
      return reply.status(400).send({
        success: false,
        error: { code: "VALIDATION_ERROR", message: parsed.error.issues[0].message },
      });
    }

    await sendTeamInviteEmail(parsed.data);
    return reply.send({ success: true });
  });

  // POST /internal/send-quote — send a quote email to the recipient
  server.post("/send-quote", async (request, reply) => {
    const parsed = QuoteSentEmailSchema.safeParse(request.body);
    if (!parsed.success) {
      return reply.status(400).send({
        success: false,
        error: { code: "VALIDATION_ERROR", message: parsed.error.issues[0].message },
      });
    }

    const { to, recipientName, quoteNumber, totalAmount, senderName, companyName } = parsed.data;
    const APP_URL = process.env.APP_URL ?? "http://localhost:3000";

    // Use the same email infrastructure as other auth emails
    const { Resend } = await import("resend");
    const resend = process.env.RESEND_API_KEY ? new Resend(process.env.RESEND_API_KEY) : null;
    const FROM = process.env.EMAIL_FROM ?? "NexCRM <noreply@nexcrm.io>";

    const subject = `Quote ${quoteNumber} from ${companyName}`;
    const html = `
      <div style="font-family:sans-serif;max-width:600px;margin:0 auto">
        <h1 style="color:#0f172a">Quote ${quoteNumber}</h1>
        <p>Hi ${recipientName},</p>
        <p><strong>${senderName}</strong> from <strong>${companyName}</strong> has sent you a quote.</p>
        <p style="font-size:24px;font-weight:bold;color:#6366f1">Total: ${totalAmount}</p>
        <p style="margin:32px 0">
          <a href="${APP_URL}/quotes"
             style="background:#6366f1;color:#fff;padding:12px 24px;border-radius:6px;text-decoration:none;font-weight:600">
            View Quote
          </a>
        </p>
        <p style="color:#64748b;font-size:13px">This quote was generated by NexCRM.</p>
      </div>`;
    const text = `Quote ${quoteNumber} from ${companyName}\n\nTotal: ${totalAmount}\n\nSent by ${senderName}`;

    if (!resend) {
      console.log(`\n[email:dev] ─────────────────────────────────────────`);
      console.log(`  To:      ${to}`);
      console.log(`  Subject: ${subject}`);
      console.log(`  Body:\n${text}`);
      console.log(`─────────────────────────────────────────────────────\n`);
    } else {
      await resend.emails.send({ from: FROM, to, subject, html, text });
    }

    return reply.send({ success: true });
  });
}
